# Configuration for GitHub PR labeler v5
# https://github.com/actions/labeler

# Label PRs that modify documentation
documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md', '**/*.mdx', 'README*']

# Label PRs that modify styles
styles:
  - changed-files:
      - any-glob-to-any-file:
          ['**/*.css', '**/*.scss', '**/*.sass', '**/styles/**', 'src/styles/**']

# Label PRs that modify components
components:
  - changed-files:
      - any-glob-to-any-file: ['src/components/**', '**/*.astro']

# Label PRs that modify layouts
layouts:
  - changed-files:
      - any-glob-to-any-file: ['src/layouts/**']

# Label PRs that modify pages
pages:
  - changed-files:
      - any-glob-to-any-file: ['src/pages/**']

# Label PRs that modify content
content:
  - changed-files:
      - any-glob-to-any-file: ['src/content/**']

# Label PRs that modify configuration
config:
  - changed-files:
      - any-glob-to-any-file:
          ['*.config.*', '*.json', '*.yml', '*.yaml', '.github/**', 'package.json', 'tsconfig.json']

# Label PRs that modify dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file: ['package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']

# Label PRs that modify CI/CD
'ci/cd':
  - changed-files:
      - any-glob-to-any-file: ['.github/workflows/**', '.husky/**']

# Label PRs that modify assets
assets:
  - changed-files:
      - any-glob-to-any-file:
          [
            'src/assets/**',
            'public/**',
            '**/*.jpg',
            '**/*.jpeg',
            '**/*.png',
            '**/*.svg',
            '**/*.gif',
            '**/*.webp',
          ]

# Label PRs that are bug fixes
bug:
  - head-branch: ['^fix/', '^hotfix/']

# Label PRs that are new features
feature:
  - head-branch: ['^feature/', '^feat/']
