name: PR Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run pre-commit checks
        run: npm run pre-commit

      - name: Run pre-push checks
        run: npm run pre-push

      - name: Check for large files
        run: |
          echo "Checking for files larger than 1MB..."
          find . -type f -size +1M -not -path './node_modules/*' -not -path './.git/*' || true

      - name: Check for TODO/FIXME comments
        run: |
          echo "Checking for TODO/FIXME comments..."
          grep -r "TODO\|FIXME" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --include="*.astro" . || true

      - name: Validate package.json
        run: |
          echo "Validating package.json..."
          node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
          echo "✓ package.json is valid JSON"

      - name: Bundle size check
        run: |
          npm run build
          echo "Build size:"
          du -sh dist/ || true

